### ISSUE TITLE
Given a Resource/Dataset profile (in JSON schema) generate a reference page and code template

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan-client-guide#2]
When I have a profile for my metadata (in json schema) I want to generate reference docs for it and/or code templates to that data scientists and data engineers in my team can get started quickly

## Acceptance

* [ ] Given a profile in JSON Schema generate a template file in Python (R,JS) as follows
* [ ] Given a profile in JSON Schema generate a reference doc in markdown or HTML (basic or nice - nice would be like image in https://github.com/frictionlessdata/forum/issues/49)

```python=
# Mandatory Fields

# lowercase alphanumeric and underscores only
name = 'sample_r_dataset2'

# display name
title = 'Sample R Dataset'

notes = 'Detailed Dataset Description'

maintainer='Dataset Maintainer Name'

maintainer_email='Dataset.Maintainer@xxx.org'

publisher='Dataset Publisher'

owner_org='yyy'

visibility='public'
# other options: 'private'

geographic_level='global'
#other options: 'national','regional','sub-national','other'

license_id='notspecified'

information_classification= 'public-public-external'
# other options: 'not_sensitive-non_confidential-internal-business', 'not_sensitive-non_confidential-internal-business', etc
```

## Tasks

* [ ] Choose whether we use JS or Python for the remaining work **ANS: probably JS**
* [ ] Find a profile to work on
  * [ ] https://specs.frictionlessdata.io/schemas/data-resource.json or https://specs.frictionlessdata.io/schemas/data-package.json
  * [ ] Create an example client one - see below @usman
* [ ] Auto generate a reference page in markdown or html using JS or script
* [ ] Auto generate a template file in Python
  * [ ] BONUS 🎱 do this in R
  * [ ] BONUS 🎱 do this in JS

### Creating an example client profile

* [ ] Find an example profile for this client as defined in e.g. ckanext-scheming for Datasets and Resources
* [ ] Convert to JSON schema and align with JSON schemas for Frictionless profiles (ie. base off those if you can)
