### ISSUE TITLE
Auto generate "init" code for a Resource/Dataset profile

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckan-client-guide#3]
When I have a profile for my metadata (in json schema) I want to generate code templates to that data scientists and data engineers in my team can get started quickly

## Acceptance

* [ ] A command line tool (or function in library) that given a profile in JSON Schema generate a template file similar to below (appropriate to language / format)
  * [ ] Python
  * [ ] R
  * [ ] JS
  * [ ] JSON
  * Recommend incorporating this into https://github.com/frictionlessdata/frictionless-py or https://github.com/frictionlessdata/frictionless-js
* [ ] Support multiple profiles (i.e. being passed a profile)

```python=
# Mandatory Fields

# lowercase alphanumeric and underscores only
name = 'sample_r_dataset2'

# display name
title = 'Sample R Dataset'

notes = 'Detailed Dataset Description'

maintainer='Dataset Maintainer Name'

maintainer_email='Dataset.Maintainer@xxx.org'

publisher='Dataset Publisher'

owner_org='yyy'

visibility='public'
# other options: 'private'

geographic_level='global'
#other options: 'national','regional','sub-national','other'

license_id='notspecified'

information_classification= 'public-public-external'
# other options: 'not_sensitive-non_confidential-internal-business', 'not_sensitive-non_confidential-internal-business', etc
```

## Tasks

* [ ] Look at https://github.com/frictionlessdata/frictionless-py
* [ ] Auto generate a template file in Python
* [ ] do this in R
* [ ] do this in JS
* [ ] Support multiple profiles
